export const CURRENCY_LIST_REQUEST: string = "CURRENCY_LIST_REQUEST";
export const CURRENCY_LIST_SUCCESS: string = "CURRENCY_LIST_SUCCESS";
export const CURRENCY_LIST_FAIL: string = "CURRENCY_LIST_FAIL";
