export const ADD_GROUPUSERS_REQUEST: string = "ADD_GROUPUSERS_REQUEST";
export const ADD_GROUPUSERS_FAIL: string = "ADD_GROUPUSERS_FAIL";
export const ADD_GROUPUSERS_SUCCESS: string = "ADD_GROUPUSERS_SUCCESS";
export const GET_USERSOFGROUP_REQUEST: string = "GET_USERSOFGROUP_REQUEST";
export const GET_USERSOFGROUP_FAIL: string = "GET_USERSOFGROUP_FAIL";
export const GET_USERSOFGROUP_SUCCESS: string = "GET_USERSOFGROUP_SUCCESS";
