export const GET_USERSOFGROUP_REQUEST: string = "GET_USERSOFGROUP_REQUEST";
export const GET_USERSOFGROUP_FAIL: string = "GET_USERSOFGROUP_FAIL";
export const GET_USERSOFGROUP_SUCCESS: string = "GET_USERSOFGROUP_SUCCESS";
