export const QUESTIONS_FAQ_LIST_REQUEST: string = "QUESTIONS_FAQ_LIST_REQUEST";
export const QUESTIONS_FAQ_LIST_SUCCESS: string = "QUESTIONS_FAQ_LIST_SUCCESS";
export const QUESTIONS_FAQ_LIST_FAIL: string = "QUESTIONS_FAQ_LIST_FAIL";
export const CREATE_QUESTION_FAQ_REQUEST: string = "CREATE_QUESTION_FAQ_REQUEST";
export const CREATE_QUESTION_FAQ_SUCCESS: string = "CREATE_QUESTION_FAQ_SUCCESS";
export const CREATE_QUESTION_FAQ_FAIL: string = "CREATE_QUESTION_FAQ_FAIL";
