export const QUESTIONS_FAQ_LIST_REQUEST: string = "QUESTIONS_FAQ_LIST_REQUEST";
export const QUESTIONS_FAQ_LIST_SUCCESS: string = "QUESTIONS_FAQ_LIST_SUCCESS";
export const QUESTIONS_FAQ_LIST_FAIL: string = "QUESTIONS_FAQ_LIST_FAIL";
